import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { BookOpen, Calculator, FileText, LogOut, Search, Users, Plus, ArrowUpRight, GraduationCap } from "lucide-react";
import { useDispatch, useSelector } from "react-redux";
import { useNavigate } from "react-router-dom";
import { logout } from "../redux/authSlice";

const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api";
const starter=[["Data Structures",4,9],["Database Systems",4,8],["Operating Systems",3,8],["Computer Networks",3,9]];

export default function Dashboard(){
 const {user,token}=useSelector(s=>s.auth),dispatch=useDispatch(),navigate=useNavigate();
 const [resources,setResources]=useState([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true);
 const [subjects,setSubjects]=useState(starter.map(([name,credits,gradePoint])=>({name,credits,gradePoint}))),[sgpa,setSgpa]=useState(null),[room,setRoom]=useState("");
 const headers=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]);
 const fetchResources=async()=>{try{setLoading(true);const r=await axios.get(`${API}/resources`,{headers,params:{search,limit:8}});setResources(r.data.resources||[])}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{if(token)fetchResources()},[token]);
 const calc=async()=>{const r=await axios.post(`${API}/academic/sgpa`,{subjects}, {headers});setSgpa(r.data.sgpa)};
 const update=(i,k,v)=>setSubjects(s=>s.map((x,j)=>j===i?{...x,[k]:k==="name"?v:Number(v)}:x));
 const add=()=>setSubjects(s=>[...s,{name:"New Subject",credits:3,gradePoint:8}]);
 const join=()=>room.trim()&&navigate(`/dashboard/rooms/${encodeURIComponent(room.trim())}`);
 return <div className="min-h-screen bg-canvas">
  <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8">
    <div className="flex items-center gap-3"><div className="rounded-xl bg-indigo-600 p-2 text-white"><GraduationCap size={21}/></div><div><b className="text-base text-navy">CGPA Booster</b><p className="text-xs text-slate-400">Student workspace</p></div></div>
    <div className="flex items-center gap-3"><div className="hidden text-right sm:block"><b className="text-sm text-slate-700">{user?.name}</b><p className="text-xs text-slate-400">{user?.course||"Student"}</p></div><button className="secondary-button px-3 py-2" onClick={()=>{dispatch(logout());navigate("/login",{replace:true})}}><LogOut size={17}/><span className="hidden sm:inline">Sign out</span></button></div>
  </div></header>
  <main className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
   <section className="rounded-3xl bg-navy p-7 text-white shadow-xl sm:p-9"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-indigo-300">Good to see you</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Welcome, {user?.name?.split(" ")[0]||"Student"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Access your study resources, calculate academic performance and connect with classmates.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Stat label="Semester" value={user?.semester||1}/><Stat label="Branch" value={user?.branch||"Not set"}/><Stat label="Resources" value={resources.length}/></div></div></section>
   <section className="mt-7 grid gap-6 lg:grid-cols-3">
    <div className="card p-6"><IconBox icon={<Calculator size={20}/>}/><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold text-navy">SGPA Calculator</h2><p className="mt-1 text-sm text-slate-500">Calculate your semester performance.</p></div>{sgpa!==null&&<div className="text-right"><p className="text-xs text-slate-400">SGPA</p><b className="text-3xl text-indigo-600">{sgpa}</b></div>}</div>
      <div className="mt-5 space-y-3">{subjects.map((s,i)=><div key={i} className="grid grid-cols-[1fr_65px_75px] gap-2"><input className="input-field px-3 py-2 text-xs" value={s.name} onChange={e=>update(i,"name",e.target.value)}/><input className="input-field px-3 py-2 text-xs" type="number" value={s.credits} onChange={e=>update(i,"credits",e.target.value)}/><input className="input-field px-3 py-2 text-xs" type="number" value={s.gradePoint} onChange={e=>update(i,"gradePoint",e.target.value)}/></div>)}</div>
      <div className="mt-5 flex gap-2"><button className="secondary-button flex-1 px-3 py-2" onClick={add}><Plus size={16}/>Add</button><button className="primary-button flex-1 px-3 py-2" onClick={calc}>Calculate</button></div>
    </div>
    <div className="card p-6"><IconBox icon={<BookOpen size={20}/>}/><h2 className="text-lg font-bold text-navy">Study Resources</h2><p className="mt-1 text-sm leading-6 text-slate-500">Find notes, PYQs, assignments and question banks.</p><div className="relative mt-5"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input-field pl-10" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&fetchResources()} placeholder="Search resources..."/></div><button className="primary-button mt-3 w-full" onClick={fetchResources}>Search resources</button><div className="mt-5 space-y-2">{loading?<p className="text-sm text-slate-400">Loading resources...</p>:resources.length?resources.slice(0,4).map(r=><a key={r._id} href={r.fileUrl} target="_blank" rel="noreferrer" className="group flex items-center justify-between rounded-xl border border-slate-100 p-3 hover:bg-indigo-50/50"><div className="min-w-0"><p className="truncate text-sm font-semibold">{r.title}</p><p className="text-xs text-slate-400">{r.type} · {r.subject}</p></div><ArrowUpRight size={16} className="text-slate-300 group-hover:text-indigo-600"/></a>):<p className="text-sm text-slate-400">No matching resources found.</p>}</div></div>
    <div className="card p-6"><IconBox icon={<Users size={20}/>}/><h2 className="text-lg font-bold text-navy">Study Rooms</h2><p className="mt-1 text-sm leading-6 text-slate-500">Join a room and collaborate with classmates in real time.</p><label className="mt-6 mb-2 block text-sm font-semibold">Room code</label><input className="input-field" value={room} onChange={e=>setRoom(e.target.value)} onKeyDown={e=>e.key==="Enter"&&join()} placeholder="e.g. dsa-sem4"/><button className="primary-button mt-4 w-full" onClick={join}>Join study room <ArrowUpRight size={17}/></button><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Room messaging is secured through your authenticated session.</div></div>
   </section>
   <section className="mt-7"><div className="card overflow-hidden"><div className="border-b border-slate-100 p-6"><h2 className="text-lg font-bold text-navy">Recent resources</h2><p className="mt-1 text-sm text-slate-500">Latest material available to your student community.</p></div>{resources.length?resources.map(r=><div key={r._id} className="flex items-center justify-between gap-4 border-b border-slate-100 p-5"><div className="flex min-w-0 items-center gap-4"><div className="rounded-xl bg-indigo-50 p-3 text-indigo-600"><FileText size={19}/></div><div className="min-w-0"><h3 className="truncate font-semibold">{r.title}</h3><p className="text-xs text-slate-400">{r.type} · {r.subject} · Semester {r.semester}</p></div></div><a href={r.fileUrl} target="_blank" rel="noreferrer" className="flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold text-indigo-600 hover:bg-indigo-50">Open <ArrowUpRight size={16}/></a></div>):<div className="p-10 text-center text-sm text-slate-400">No resources available yet.</div>}</div></section>
  </main></div>;
}
function Stat({label,value}){return <div className="rounded-2xl border border-white/10 bg-white/5 px-5 py-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 max-w-28 truncate text-xl font-bold">{value}</p></div>}
function IconBox({icon}){return <div className="mb-4 inline-flex rounded-xl bg-indigo-50 p-2.5 text-indigo-600">{icon}</div>}